# Generated by Django 3.2.7 on 2021-11-07 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=12, unique=True, verbose_name='Логин пользователя')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Почта пользователя')),
                ('password', models.CharField(max_length=12, verbose_name='Пароль пользователя')),
            ],
        ),
        migrations.CreateModel(
            name='CollectionsMemes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание мема')),
                ('photo', models.ImageField(upload_to='user/%Y/%m/%d/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='base.users', verbose_name='Автор мема')),
            ],
        ),
    ]
